name = "akiraxtkd"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]  
compatibility_flags = ["nodejs_compat"]
